/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.enginehub.crankcase

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.create

open class CrankcasePlugin: Plugin<Project> {
    override fun apply(project: Project) {
        project.extensions.create<CrankcaseExtension>("crankcase")
    }
}
